<?php

require_once APP_TESTS_LIB . '/testcase.php';

/**
 * Generated by PHPUnit_SkeletonGenerator on 2017-03-17 at 05:55:31.
 *
 * @group framework
 * @group framework-kernel
 */
class APP_View_Page_Test extends APP_UnitTestCase {

	/**
	 * @var APP_View_Page
	 */
	protected $object;

	/**
	 * Tears down the fixture, for example, closes a network connection.
	 * This method is called after a test is executed.
	 */
	public function tearDown() {
		parent::tearDown();
		APP_View_Page::uninstall();
	}

    public function post_types_data() {
        return array(
            array( 'page' ),
            array( 'post' ),
        );
    }

	/**
	 * @dataProvider post_types_data
	 */
	public function test_condition( $ptype ) {
		$template = "test_get_{$ptype}_id.php";
		$page     = new APP_View_Page( $template, 'Test Template', $ptype );

		APP_View_Page::install();

		$this->go_to( get_permalink( $page->get_page_id() ) );
		$this->assertTrue( $page->condition() );
	}

	/**
	 * @covers APP_View_Page::pre_template_include
	 * @todo   Implement testPre_template_include().
	 */
	public function test_pre_template_include() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @dataProvider post_types_data
	 */
	public function test_get_page_id( $ptype ) {
		$template = "test_get_{$ptype}_id.php";
		$page     = new APP_View_Page( $template, 'Test Template', $ptype );

		APP_View_Page::install();

		$page_id = APP_View_Page::_get_page_id( $template );

		$this->assertEquals( $page_id, $page->get_page_id() );
	}

	public function test_get_template() {
		$template = array( 'test_get_template_0.php', 'test_get_template_1.php' );
		$page     = new APP_View_Page( $template, 'Test Template' );

		APP_View_Page::install();

		$this->assertEquals( $page->get_template(), $template[0] );
	}

	/**
	 * @dataProvider post_types_data
	 */
	public function test__get_page_id( $ptype ) {
		$template = "test_get_{$ptype}_id.php";
		$page     = new APP_View_Page( $template, 'Test Template', $ptype );

		APP_View_Page::install();

		$page_id = APP_View_Page::_get_page_id( $template );

		$this->assertEquals( $page->get_page_id(), $page_id );
	}

	/**
	 * @dataProvider post_types_data
	 */
	public function test_install( $ptype ) {
		$template = "test_get_{$ptype}_id.php";
		$page     = new APP_View_Page( $template, 'Test Template', $ptype );

		APP_View_Page::install();

		$page_id  = APP_View_Page::_get_page_id( $template );
		$page_obj = get_post( $page_id );

		$this->assertInstanceOf( 'WP_Post', $page_obj );
		$this->assertEquals( $ptype, $page_obj->post_type );
	}

	/**
	 * @dataProvider post_types_data
	 */
	public function test_uninstall( $ptype ) {
		$template = "test_get_{$ptype}_id.php";
		$page     = new APP_View_Page( $template, 'Test Template', $ptype );
		$page_id  = $page->get_page_id();

		APP_View_Page::install();
		APP_View_Page::uninstall();

		$page_obj = get_post( $page_id );

		$this->assertEmpty( APP_View_Page::_get_page_id( $template ) );
		$this->assertEmpty( $page_obj );
	}

	/**
	 * @dataProvider post_types_data
	 */
	public function test__register_new_template( $ptype ) {
		$this->go_to( admin_url() );

		$template = "test__register_new_{$ptype}_templates.php";
		$page     = new APP_View_Page( $template, 'Test Template', $ptype );

		APP_View_Page::install();

		$new_templates = wp_get_theme()->get_page_templates( null, $ptype );

		$this->assertArrayHasKey( $template, $new_templates );
	}

	/**
	 * @covers APP_View_Page::_preserve_template
	 * @todo   Implement test_preserve_template().
	 */
	public function test__preserve_template() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers APP_View_Page::_restore_preserved_template
	 * @todo   Implement test_restore_preserved_template().
	 */
	public function test__restore_preserved_template() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers APP_View_Page::meta_tags
	 * @todo   Implement testMeta_tags().
	 */
	public function test_meta_tags() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

}
